// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogHr_QUXqD-FZRgv4c-Ehgekv70ZWESs',
    appId: '1:964881487423:web:511e3e245d353d7a15ca8a',
    messagingSenderId: '964881487423',
    projectId: 'archis-academy',
    authDomain: 'archis-academy.firebaseapp.com',
    storageBucket: 'archis-academy.firebasestorage.app',
    measurementId: 'G-W3LJREQXS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZE4AnIu3Kgf2URRaxSy_WoamHX0V3_OM',
    appId: '1:964881487423:android:0ce39e8930e4f8c115ca8a',
    messagingSenderId: '964881487423',
    projectId: 'archis-academy',
    storageBucket: 'archis-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfAMgRgzJY86lzru2TjSJfAMsoPwO0Yg',
    appId: '1:964881487423:ios:cb3fde25b83b5ee615ca8a',
    messagingSenderId: '964881487423',
    projectId: 'archis-academy',
    storageBucket: 'archis-academy.firebasestorage.app',
    iosBundleId: 'com.example.archisAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxfAMgRgzJY86lzru2TjSJfAMsoPwO0Yg',
    appId: '1:964881487423:ios:cb3fde25b83b5ee615ca8a',
    messagingSenderId: '964881487423',
    projectId: 'archis-academy',
    storageBucket: 'archis-academy.firebasestorage.app',
    iosBundleId: 'com.example.archisAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCogHr_QUXqD-FZRgv4c-Ehgekv70ZWESs',
    appId: '1:964881487423:web:806dfb3e0fcf4cfb15ca8a',
    messagingSenderId: '964881487423',
    projectId: 'archis-academy',
    authDomain: 'archis-academy.firebaseapp.com',
    storageBucket: 'archis-academy.firebasestorage.app',
    measurementId: 'G-9LYMVH7JQG',
  );
}
