platform :ios, '13.0'

# Flutter'ın kendi iç ayarlarını okuduğu zorunlu alan
import_with_filter = File.expand_path(File.join('..', '..', '.symlinks', 'plugins'))
if File.exist?(import_with_filter)
  Dir.glob(File.join(import_with_filter, '*', 'ios', 'Podfile')).each do |podfile|
    eval(File.read(podfile), binding)
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__file__))
end

post_install do |runner|
  runner.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
